version: '3.0'
services:
    batch0:
        image: frontera:latest
        container_name: batch0
        tty: true
    batch1:
        image: frontera:latest
        container_name: batch1
        tty: true
    consumer0:
        image: frontera:latest
        container_name: consumer0
        tty: true
    consumer1:
        image: frontera:latest
        container_name: consumer1
        tty: true
    strategy0:
        image: frontera:latest
        container_name: strategy0
        tty: true
    strategy1:
        image: frontera:latest
        container_name: strategy1
        tty: true
    spider0:
        image: frontera:latest
        container_name: spider0
        tty: true
    spider1:
        image: frontera:latest
        container_name: spider1
        tty: true
