# mongod.conf

# for documentation of all options, see:
#   http://docs.mongodb.org/manual/reference/configuration-options/

# Where and how to store data.
storage:
  dbPath: /data/db
  journal:
    enabled: true
  engine: "wiredTiger"
  directoryPerDB: true
  wiredTiger:
      engineConfig:
          cacheSizeGB: 10
          directoryForIndexes: true
          statisticsLogDelaySecs: 0
      collectionConfig:
          blockCompressor: "snappy"
      indexConfig:
          prefixCompression: true

# where to write logging data.
#systemLog:
#  destination: file
#  logAppend: true
#  path: /var/log/mongodb/mongod.log

# network interfaces
net:
  port: 27018
  bindIp: 0.0.0.0

# how the process runs
processManagement:
  timeZoneInfo: /usr/share/zoneinfo
#  fork: true  # fork and run in background
#  pidFilePath: /var/run/mongodb/mongod.pid  # location of pidfile

security:
  authorization: disabled

#operationProfiling:

replication:
  replSetName: rs2

sharding:
  clusterRole: shardsvr

## Enterprise-Only Options:

#auditLog:

#snmp:
