version: '3'
services:
    seed:
        image: cassandra:3.11.2
        container_name: csdr
        environment:
            - CASSANDRA_BROADCAST_ADDRESS=${HOST_IP}
            - CASSANDRA_SEEDS=192.168.88.155
        ports:
            - "9042:9042"
            - "9160:9160"
            - "7000:7000"
