version: '3'
services:
    mongod_rs0:
        image: mongo:4.0.0-xenial
        container_name: mongod_rs0
        command: ["mongod", "-f", "/etc/mongod_rs0.conf"]
        ports:
            - "27018:27018"
        volumes:
            - ./etc/mongod_rs0.conf:/etc/mongod_rs0.conf
    mongod_rs1:
        image: mongo:4.0.0-xenial
        container_name: mongod_rs1
        command: ["mongod", "-f", "/etc/mongod_rs1.conf"]
        ports:
            - "27028:27018"
        volumes:
            - ./etc/mongod_rs1.conf:/etc/mongod_rs1.conf
